---
title: "`r params$title`"
report-class: commodity
output:
  html_document:
    self_contained: true
    md_extensions: "-native_divs-native_spans"
  pdf_document:
    latex_engine: xelatex
  word_document: default
params:
  title:        "Commodity"
  name:         ""
  desc:         ""
  class:        "commodity"
  image_file:   NULL
  logos:        NULL
  info_df:      NULL
  main_plot:    NULL
  limtype_note: NULL
  props_df:     NULL
  emis_df:      NULL
  agg_df:       NULL
header-includes:
  - \usepackage{booktabs}
---

```{r en-setup, include=FALSE}
library(ggplot2)

fmt <- energyRt::report_setup()
tbl <- function(df, caption = NULL, digits = 4L, ...)
  energyRt::report_tbl(df, caption, digits, output = fmt, ...)
emit_img <- function(path, frac = 1)
  energyRt::report_img(path, frac, output = fmt)
```

```{r en-css, results='asis'}
energyRt::report_css(fmt)
```

```{r en-logo, results='asis'}
if (length(params$logos) > 0) {
  energyRt::report_img_row(params$logos, frac_total = 0.9, output = fmt)
}
```

```{r en-header, results='asis'}
energyRt::report_header(params$name, params$desc,
                        image_file = params$image_file, output = fmt)
```

```{r en-info, results='asis'}
energyRt::report_sec("Key facts", output = fmt)
tbl(params$info_df)
if (!is.null(params$limtype_note)) cat(params$limtype_note, "\n\n")
```

```{r en-props, results='asis', eval=!is.null(params$props_df)}
tbl(params$props_df, caption = "Properties")
```

```{r en-emis, results='asis', eval=!is.null(params$emis_df)}
energyRt::report_sec("Emission factors", output = fmt)
tbl(params$emis_df, max_rows = 25)
```

```{r en-emis-plot, results='asis', eval=!is.null(params$main_plot)}
emit_img(energyRt::report_plot_png(params$main_plot, 6, 3.2), 0.85)
```

```{r en-agg, results='asis', eval=!is.null(params$agg_df)}
tbl(params$agg_df, caption = "Aggregated members", max_rows = 25)
```
