---
title: "`r params$title`"
report-class: constraint
output:
  html_document:
    self_contained: true
    md_extensions: "-native_divs-native_spans"
  pdf_document:
    latex_engine: xelatex
  word_document: default
params:
  title:       "Constraint"
  name:        ""
  desc:        ""
  class:       "constraint"
  image_file:  NULL
  logos:       NULL
  info_df:     NULL
  main_plot:   NULL
  eq_text:     NULL
  summands_df: NULL
  rhs_df:      NULL
header-includes:
  - \usepackage{booktabs}
---

```{r en-setup, include=FALSE}
library(ggplot2)

fmt <- energyRt::report_setup()
tbl <- function(df, caption = NULL, digits = 4L, ...)
  energyRt::report_tbl(df, caption, digits, output = fmt, ...)
emit_img <- function(path, frac = 1)
  energyRt::report_img(path, frac, output = fmt)
```

```{r en-css, results='asis'}
energyRt::report_css(fmt)
```

```{r en-logo, results='asis'}
if (length(params$logos) > 0) {
  energyRt::report_img_row(params$logos, frac_total = 0.9, output = fmt)
}
```

```{r en-header, results='asis'}
energyRt::report_header(params$name, params$desc,
                        image_file = params$image_file, output = fmt)
```

```{r en-eq, results='asis'}
energyRt::report_sec("Equation", output = fmt)
tbl(params$info_df)
if (!is.null(params$eq_text)) cat("`", params$eq_text, "`\n\n", sep = "")
```

```{r en-summands, results='asis', eval=!is.null(params$summands_df)}
tbl(params$summands_df, caption = "Summands (left-hand side)")
```

```{r en-rhs, results='asis', eval=!is.null(params$rhs_df)}
tbl(params$rhs_df, caption = "Right-hand side", max_rows = 30)
```

```{r en-rhs-plot, results='asis', eval=!is.null(params$main_plot)}
emit_img(energyRt::report_plot_png(params$main_plot, 6.5, 3.2), 0.9)
```
