---
title: "`r params$title`"
report-class: weather
output:
  html_document:
    self_contained: true
    md_extensions: "-native_divs-native_spans"
  pdf_document:
    latex_engine: xelatex
  word_document: default
params:
  title:           "Weather"
  name:            ""
  desc:            ""
  class:           "weather"
  image_file:      NULL
  logos:           NULL
  info_df:         NULL
  main_plot:       NULL
  stats_df:        NULL
  weather_head_df: NULL
header-includes:
  - \usepackage{booktabs}
---

```{r en-setup, include=FALSE}
library(ggplot2)

fmt <- energyRt::report_setup()
tbl <- function(df, caption = NULL, digits = 4L, ...)
  energyRt::report_tbl(df, caption, digits, output = fmt, ...)
emit_img <- function(path, frac = 1)
  energyRt::report_img(path, frac, output = fmt)
```

```{r en-css, results='asis'}
energyRt::report_css(fmt)
```

```{r en-logo, results='asis'}
if (length(params$logos) > 0) {
  energyRt::report_img_row(params$logos, frac_total = 0.9, output = fmt)
}
```

```{r en-header, results='asis'}
energyRt::report_header(params$name, params$desc,
                        image_file = params$image_file, output = fmt)
```

```{r en-info, results='asis'}
energyRt::report_sec("Key facts", output = fmt)
tbl(params$info_df)
```

```{r en-hero, results='asis', eval=!is.null(params$main_plot)}
emit_img(energyRt::report_plot_png(params$main_plot, 7.5, 4.2), 1)
```

```{r en-stats, results='asis', eval=!is.null(params$stats_df)}
tbl(params$stats_df, caption = "Summary by region", max_rows = 30)
```

```{r en-head, results='asis', eval=!is.null(params$weather_head_df)}
tbl(params$weather_head_df, caption = "Data (first rows)", max_rows = 20)
```
